name: eye-anal
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - packaging=24.2
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=72.1.0
  - sip=6.10.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tornado=6.4.2
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - argcomplete==3.6.2
      - attrs==25.3.0
      - black==25.1.0
      - click==8.1.8
      - datamodel-code-generator==0.30.1
      - flexcache==0.3
      - flexparser==0.4
      - genson==1.3.0
      - h5py==3.13.0
      - inflect==7.5.0
      - isort==6.0.1
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - markupsafe==3.0.2
      - mcspydatatools==0.4.3
      - more-itertools==10.7.0
      - mypy-extensions==1.1.0
      - pandas==2.2.3
      - pathspec==0.12.1
      - pint==0.24.4
      - platformdirs==4.3.7
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rpds-py==0.24.0
      - six==1.17.0
      - tabulate==0.9.0
      - typeguard==4.4.2
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
